#! /bin/sh

libdir=$1
targets=$2

echo tmp>tmp~
echo tmp~

for i in *.o *.a *~ *.bak *.wav $targets core a.out gmon.out matlab.in tmp.0* DEADJOE dmalloc hackfile config.status libepos.so.* said.* say epos eposm vrfy; do
	if [ -f $i ]; then
		echo $i
	fi
done

if [ -d $libdir ]; then
	find $libdir -name \*.old
	find $libdir -name \*.local
	find $libdir -name \*~
fi
find .. -name \*~
