all monolith mh dos dist clean distclean say epos static gdb tgz install date pg cfgsync dos1250 dos1252 dospc2 dosil1 dosil2 doskam doskoi8 dosascii dosmac dosvga: % : Makefile.in
	@sh ./configure
	@make $*
